### PR TITLE
Adding a destroy method;

### PR DESCRIPTION
**Pull request by seangates**

### CODE REVIEW

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
As mentioned in https://github.com/makeup-js/makeup-roving-tabindex/pull/1#pullrequestreview-224088663, let's keep the scope of this to just adding a destroy method, as per the PR title.

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
Line 17 needs removing:

this._items = Util.nodeListToArray(this._el.querySelectorAll(this._itemSelector));

(This was a tricky one to spot via manual test page. Sorry for the lack of unit tests here.)

**Comment by seangates** [comment]
Removed.

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
Please also bump the navigation-emitter version in this package too.

**Comment by seangates** [comment]
Thanks. Done.

**Review by ianmcburnie — APPROVED** [review]

**Pull request merged**
